#!/usr/bin/env bash
# Единый перенос живого стенда ITles (шлюз + симулятор парка) с песочницы Zo на VPS.
# Запускать НА VPS от обычного пользователя (agentuser):
#
#   STAND_KEY='itg_...' bash stand-migrate-vps.sh
#
# STAND_KEY — ключ шлюза вида itg_… (Настройки → Ключи шлюзов; хэш уже зарегистрирован в БД).
# Скрипт идемпотентен: повторный запуск обновляет код/данные и перезапускает процессы.
#
# Что делает:
#   1) клон/обновление репо raulwulff6769/framework-lab @otschet-current (тот же клон, где сайт);
#   2) stand/stand.env: API = локальный сервер сайта (http://127.0.0.1:3000), STAND_ID прежний
#      (stand-vps) — карточка стенда в кабинете не задваивается;
#   3) данные стенда (.stand/stand-state.json — счётчики моточасов/пробега, mappings.json —
#      конфиг датчиков Galileosky) восстанавливаются из вшитых ниже base64 — телеметрия в БД
#      (Neon) уже общая, поэтому история 30 дней переносится автоматически;
#   4) запуск stand/run.sh (супервизор шлюза и стенда) + @reboot в cron;
#   5) проверки: порты шлюза слушаются, стенд отчитался в API (HTTP 200).
#
# Очередь неотправленных пакетов (gateway-queue.sqlite3) НЕ переносится: пока песочница Zo ещё
# работает, её шлюз дольёт очередь в API сам (ключ валиден). После запуска на VPS стенд
# продолжает с текущего момента — разрыва в истории не будет, если сначала дать Zo-стенду
# выкачать очередь до нуля (status .stand/gateway-status.json → queue: 0).
set -euo pipefail

APP_DIR="${APP_DIR:-$HOME/itles}"
BRANCH="${BRANCH:-otschet-current}"
REPO="${REPO:-https://github.com/raulwulff6769/framework-lab.git}"
API_URL="${API_URL:-http://127.0.0.1:3000}"
STAND_ID="${STAND_ID:-stand-vps}"
HOST_LABEL="${HOST_LABEL:-VPS Singapore (Tencent)}"

say(){ printf '\n\033[1;36m== %s ==\033[0m\n' "$1"; }
[ -n "${STAND_KEY:-}" ] || { echo "!! задайте STAND_KEY (ключ шлюза itg_...) перед запуском"; exit 1; }
command -v python3 >/dev/null || { echo "!! нужен python3 (apt-get install -y python3)"; exit 1; }
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' || { echo "!! нужен Python 3.10+"; exit 1; }

say "1) код стенда: $APP_DIR @ $BRANCH"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" fetch --depth 1 origin "$BRANCH"
  git -C "$APP_DIR" checkout -q -B "$BRANCH" "origin/$BRANCH"
else
  git clone --depth 1 -b "$BRANCH" "$REPO" "$APP_DIR"
fi
git -C "$APP_DIR" log --oneline -1

say "2) конфиг stand.env (API=$API_URL)"
ENV="$APP_DIR/stand/stand.env"
cat > "$ENV" <<EOF
ITLES_API_URL=$API_URL
STAND_KEY=$STAND_KEY
STAND_ID=$STAND_ID
STAND_HOST_LABEL="$HOST_LABEL"
STAND_HISTORY_DAYS=30
TRACCAR_HOST=demo.traccar.org
TRACCAR_PORT_TELTONIKA=5027
TRACCAR_WEB=https://demo.traccar.org
EOF
chmod 600 "$ENV"

say "3) состояние парка и конфиг датчиков (из песочницы Zo)"
DATA="$APP_DIR/.stand"
mkdir -p "$DATA" && chmod 700 "$DATA"
printf '%s' 'eyJ2ZXJzaW9uIjogMSwgInNhdmVkX2F0IjogMTc5MDY1MjYwOC4xNjk4NzksICJ1bml0cyI6IHsiODY4MTgzMDMwODI4OTA0IjogeyJ0IjogMTc5MDY1MjYwOCwgImhvdXJzIjogNDQ1NS41NDkyMTY4ODA3NzcsICJvZG9fbSI6IDMwMzY2OTcxLjA4NTExMTYzMywgImduc3Nfb2RvX20iOiAzOTUwOTcxLjA4NTExMjI3MSwgImZ1ZWxfdXNlZF9sIjogMTMyMTExLjI0MzIyODQwMTUyLCAiZnVlbF9sIjogOTA4LjQ4MTc1OTU5OTMzMDQsICJpbmRleCI6IDc1MDl9LCAiODYwMjUxMDU1NzgzMDQ1IjogeyJ0IjogMTc5MDY1MjYwOCwgImhvdXJzIjogNTEzMy4yNTY4Nzg4NTM2MzEsICJvZG9fbSI6IDM0ODc5MjkxLjk2Mjc0ODQxNiwgImduc3Nfb2RvX20iOiA0MDc3MDkxLjk2Mjc0NjI5NCwgImZ1ZWxfdXNlZF9sIjogMTUwOTUzLjI3NzQ5OTQxMDQ0LCAiZnVlbF9sIjogNzY2LjQ0MTg5ODY1NTk0MTMsICJpbmRleCI6IDY3MDF9LCAiODY4MTgzMDM2NDU3ODU2IjogeyJ0IjogMTc5MDY1MjYwOCwgImhvdXJzIjogMTczNi40MTI4Njc3MTk1OTcyLCAib2RvX20iOiAxMTU5NDIwOC41ODAzMDAxNjUsICJnbnNzX29kb19tIjogMjY0NTAwOC41ODAyOTkzODU0LCAiZnVlbF91c2VkX2wiOiA0ODI4MC45MDE4NjE3MDQ3OCwgImZ1ZWxfbCI6IDgwMy4zMjY0MjE0NzI1ODEzLCAiaW5kZXgiOiA1ODkyfSwgIjg2ODE4MzAzMzQwMTk1NiI6IHsidCI6IDE3OTA2NTI2MDgsICJob3VycyI6IDI2Nzg3LjU3ODM3MDE5OTc0NiwgIm9kb19tIjogMTcyMTYwMjUyLjg4OTg3NjYsICJnbnNzX29kb19tIjogMTYyNzU1Mi44ODk4ODExODc0LCAiZnVlbF91c2VkX2wiOiAyNjc0MTAuOTU2MDI3MTY0MzYsICJmdWVsX2wiOiAyNDYuNDExMDA2NzM0Mjg3NDQsICJpbmRleCI6IDM2OTd9LCAiODYwMjUxMDU4OTc3NzY4IjogeyJ0IjogMTc5MDY1MjYwOCwgImhvdXJzIjogMTU3NDMuOTk1MDM2NTM1MDksICJvZG9fbSI6IDEwMTE5NTcxNS4yMzQzMjMxNiwgImduc3Nfb2RvX20iOiAyMjQ4MTY1LjIzNDMyMzE2MywgImZ1ZWxfdXNlZF9sIjogMTI5MDE2LjQ2MDU0MDAzNzEsICJmdWVsX2wiOiA4Mi42MDkxNDQ5OTg2NjU1LCAiaW5kZXgiOiA1NjIzfSwgIjcwMTEwNDMiOiB7InQiOiAxNzkwNjUyNjA4LCAiaG91cnMiOiAyMzY2My4yOTc0Nzk3MTY5NiwgIm9kb19tIjogMTY0Mjk2NjY5Ljg4MTYxODYyLCAiZ25zc19vZG9fbSI6IDEzNDQ0MDE5Ljg4MTYxNzE4MSwgImZ1ZWxfdXNlZF9sIjogNDc3MzQzLjgxODg0NTc1MzMsICJmdWVsX2wiOiAzMDQuNTMxMzIwOTk3NzIyMywgImluZGV4IjogOTM3NH0sICI4NjgxODMwMzY5NjE4NDAiOiB7InQiOiAxNzkwNjUyNjA4LCAiaG91cnMiOiAzNDUyMC42NDIzMzU3MjQ2OCwgIm9kb19tIjogMjI3MzIzMDMwLjMwMzU0OCwgImduc3Nfb2RvX20iOiA2NzQ4NzgwLjMwMzU1NTgyOSwgImZ1ZWxfdXNlZF9sIjogMTQ5MTAyNi41OTYzNzczMDA2LCAiZnVlbF9sIjogNjI3LjMwMDA5ODA3NjA5NzgsICJpbmRleCI6IDg1MzN9LCAiODYwMjUxMDUzMTA3Mzk1IjogeyJ0IjogMTc5MDY1MjYwOCwgImhvdXJzIjogMTI3MDguMTkzMjA3Mjk5MTUsICJvZG9fbSI6IDgxNTg4MjgyLjU5MTAwNDU3LCAiZ25zc19vZG9fbSI6IDI1Nzc1MzIuNTkxMDAwOTI5LCAiZnVlbF91c2VkX2wiOiAxNjMzMTYuMTg4NzIxNjU4OTIsICJmdWVsX2wiOiAxODQuMzIyMDE0MjMyNjA1NywgImluZGV4IjogMTA2MjR9LCAiODY4MTgzMDMyNzg5NjgyIjogeyJ0IjogMTc5MDY1MjYwOCwgImhvdXJzIjogMTM5NTEuNDI1MzM0NDE1ODUsICJvZG9fbSI6IDAuMCwgImduc3Nfb2RvX20iOiAxMzQ0NzE2LjExMzQ3MTU5NSwgImZ1ZWxfdXNlZF9sIjogMjcwNjQ4LjYyMzI4MzIxODI0LCAiZnVlbF9sIjogMzUzLjEwNzU4NDI1MzE2MjYsICJpbmRleCI6IDk4MDZ9LCAiMzUyMTAyMTI3NDA4MjgyIjogeyJ0IjogMTc5MDY1MjYwOCwgImhvdXJzIjogMjA1MS45NTE0OTc5ODkyMzA2LCAib2RvX20iOiAxMzc2ODUxMS4wOTcyOTE0ODQsICJnbnNzX29kb19tIjogMTI1NTM2MS4wOTcyOTEzOTI3LCAiZnVlbF91c2VkX2wiOiA1OTg1OS45NDMyMjI3NDgwNjUsICJmdWVsX2wiOiA1NzIuODc4MjM4MTUzNjcxNiwgImluZGV4IjogMjIyNn0sICIzNTIxMDIxMjQ2MTI3MjAiOiB7InQiOiAxNzkwNjUyNjA4LCAiaG91cnMiOiA0ODU3LjEyMjEzODYyNjQwMywgIm9kb19tIjogMC4wLCAiZ25zc19vZG9fbSI6IDY0MzAxLjg5Nzc4OTIwMjE3LCAiZnVlbF91c2VkX2wiOiAxMDkxNzkuOTI0MDc1NTQ1MDksICJmdWVsX2wiOiA0MTUuNzkyMTA4ODA3NzMwMiwgImluZGV4IjogNTU0fSwgIjM1MjEwMjEyMDA0NjM2MCI6IHsidCI6IDE3OTA2NTI2MDgsICJob3VycyI6IDQ2MjkuODIyMDIwMDc1NzEzLCAib2RvX20iOiAyOTk3Mzk5OC42NzI2OTA3MDQsICJnbnNzX29kb19tIjogODU5ODQ4LjY3MjY5MDE3OTEsICJmdWVsX3VzZWRfbCI6IDU5MTU2LjMxOTk5OTg1OTc5LCAiZnVlbF9sIjogNzQuMTEyODM1NjM4Njg4MTcsICJpbmRleCI6IDI5NDF9LCAiODY4MTgzMDMxMjQ1NjcwIjogeyJ0IjogMTc5MDY1MjYwOCwgImhvdXJzIjogODEwMi40NzI5OTk1NTExOTMsICJvZG9fbSI6IDUyMTczNzIzLjMzNDU5ODUyLCAiZ25zc19vZG9fbSI6IDYwNjYyMy4zMzQ1OTc5MzI5LCAiZnVlbF91c2VkX2wiOiA4MDgxOC44MDgxMjMxMTcxOCwgImZ1ZWxfbCI6IDI2NC4xNzE2OTYzNjI5MDI4LCAiaW5kZXgiOiAxNDg4fSwgIjg2ODE4MzAzMTI0NTY4OCI6IHsidCI6IDE3OTA2NTI2MDgsICJob3VycyI6IDcyOTkuODM0MTEwNjYyMzk3NSwgIm9kb19tIjogNDcyMTk3OTQuNTU3ODg4MzIsICJnbnNzX29kb19tIjogODI4NjQ0LjU1Nzg4ODY0NDMsICJmdWVsX3VzZWRfbCI6IDU5NTYzLjIzNjE2NjgyNjEzLCAiZnVlbF9sIjogNTMuNTQxNTQ5MjI2NTYwODA0LCAiaW5kZXgiOiAxOTkwfSwgIjg2ODE4MzAzMTI0NTY5NiI6IHsidCI6IDE3OTA2NTI2MDgsICJob3VycyI6IDYwNzMuMDE0MzMxMzUxNTM1LCAib2RvX20iOiA0MTgxNzY0NS44MTIwNjc2MSwgImduc3Nfb2RvX20iOiAzMjE3Mzk1LjgxMjA2NzUxOSwgImZ1ZWxfdXNlZF9sIjogMTIyMzQ5LjUwMzI0MDU5Nzg5LCAiZnVlbF9sIjogNDQxLjEwMjY2NzA3NTUxMzg2LCAiaW5kZXgiOiAyMzk0fSwgIktNVFBDMjI5TDAxMDQ1MTIzIjogeyJ0IjogMTc5MDY1MjYwOCwgImhvdXJzIjogNTE0MC4xNjk2NDc5NTk5MzQsICJvZG9fbSI6IDAuMCwgImduc3Nfb2RvX20iOiA3NDMzOS44MjY5NjcyOTk4NCwgImZ1ZWxfdXNlZF9sIjogMTE1MjkyLjM4MzA5MDA5MjE1LCAiZnVlbF9sIjogNTU4LjMxMTcwNzk4NjE2OTQsICJpbmRleCI6IDU3OX0sICJLTVRIRDQ2NUswNzAzMjk4MSI6IHsidCI6IDE3OTA2NTI2MDgsICJob3VycyI6IDY5NjUuNDIzOTM0MTUxMDg0LCAib2RvX20iOiA0NjQ5NzA0My45Mzc1ODcyOSwgImduc3Nfb2RvX20iOiAyNjM2MzQzLjkzNzU4Njk5NzYsICJmdWVsX3VzZWRfbCI6IDMwMzQzMy4zMjUyMTMwNDU0NiwgImZ1ZWxfbCI6IDU1OS4wMzYxMzI3NjY0NDYxLCAiaW5kZXgiOiAzMTI0fSwgIktNVFdBNDcwVjY1MDIxNDU1IjogeyJ0IjogMTc5MDY1MjYwOCwgImhvdXJzIjogNDEwMy40MTk3NjUzNzIwMTgsICJvZG9fbSI6IDI2NDIwODEwLjgxMjIyMTkxNSwgImduc3Nfb2RvX20iOiA3MDc0NjAuODEyMjIxMzYyNCwgImZ1ZWxfdXNlZF9sIjogNTI1NTQuMTc0NDExMzA2MjcsICJmdWVsX2wiOiAxOTMuMjk1MTM3MjIxMzU3NzUsICJpbmRleCI6IDI5ODZ9LCAiODY4MTgzMDM0NTEyODk2IjogeyJ0IjogMTc5MDY1MjYwOCwgImhvdXJzIjogNTcxMi45OTAxMzYyNzY2NDYsICJvZG9fbSI6IDAuMCwgImduc3Nfb2RvX20iOiA0NDE0NS40Njc0MDQ3ODcwMSwgImZ1ZWxfdXNlZF9sIjogMTI3NzUwLjc0NTMyODcyMTM0LCAiZnVlbF9sIjogMTc3LjcxNDM0ODU4OTgyNzcsICJpbmRleCI6IDQwNX0sICI4NjAyNTEwNTIyODg2MTQiOiB7InQiOiAxNzkwNjUyNjA4LCAiaG91cnMiOiA2ODk4LjIzMzkyMzU3ODE3NywgIm9kb19tIjogNDU2OTU3NjEuMDUyODcyNjM1LCAiZ25zc19vZG9fbSI6IDIyMjM3NjEuMDUyODcxNTcxNCwgImZ1ZWxfdXNlZF9sIjogMzAwMzc4Ljk3NjY3OTUyOTUsICJmdWVsX2wiOiAxNDguMzIyNjcwNjM4NTQxNDcsICJpbmRleCI6IDMzOTl9LCAiNzAxMTEwMiI6IHsidCI6IDE3OTA2NTI2MDgsICJob3VycyI6IDQ0NzcuNjQ3MTc3ODgxNjQ4LCAib2RvX20iOiAwLjAsICJnbnNzX29kb19tIjogMzczNjU5LjYyNTg1NzQyNjIsICJmdWVsX3VzZWRfbCI6IDg2NTM3Ljk0MjI3NzAxNzEyLCAiZnVlbF9sIjogMjA3LjcwOTUxMjk5MjIwODk0LCAiaW5kZXgiOiAyODE0fX19' | base64 -d > "$DATA/stand-state.json"
printf '%s' 'ewogIjg2ODE4MzAzMDgyODkwNCI6IHsKICAic2Vuc29ycyI6IHsKICAgInJwbSI6IHsKICAgICJ0YWciOiAxOTMsCiAgICAiYnl0ZV9vZmZzZXQiOiAyLAogICAgImJ5dGVzIjogMiwKICAgICJzY2FsZSI6IDAuMTI1CiAgIH0sCiAgICJjb29sYW50X3RlbXBfYyI6IHsKICAgICJ0YWciOiAxOTMsCiAgICAiYnl0ZV9vZmZzZXQiOiAxLAogICAgImJ5dGVzIjogMSwKICAgICJvZmZzZXQiOiAtNDAKICAgfSwKICAgImZ1ZWxfdXNlZF9sIjogewogICAgInRhZyI6IDE5MiwKICAgICJzY2FsZSI6IDAuNQogICB9LAogICAiZW5naW5lX2xvYWRfcGN0IjogewogICAgInRhZyI6IDE2MAogICB9LAogICAib2lsX3ByZXNzdXJlX2twYSI6IHsKICAgICJ0YWciOiAxNzYKICAgfSwKICAgImJhdHRlcnlfdiI6IHsKICAgICJ0YWciOiA2NSwKICAgICJzY2FsZSI6IDAuMDAxCiAgIH0sCiAgICJpbXBsZW1lbnRfb24iOiB7CiAgICAidGFnIjogNzAsCiAgICAiYml0IjogMQogICB9LAogICAiZnVlbF9sZXZlbF9sIjogewogICAgInRhZyI6IDk2LAogICAgInRhYmxlIjogWwogICAgIFsKICAgICAgMCwKICAgICAgMAogICAgIF0sCiAgICAgWwogICAgICA0MDk1LAogICAgICAxMDAwCiAgICAgXQogICAgXQogICB9CiAgfQogfSwKICI4NjAyNTEwNTU3ODMwNDUiOiB7fSwKICI4NjgxODMwMzY0NTc4NTYiOiB7CiAgInBhcmFtX2hvdXJzIjogewogICAiZW5nX2hvdXJzIjogImVjdSIKICB9LAogICJwYXJhbV9taWxlYWdlIjogewogICAiY2FuX2Rpc3Rfa20iOiAiZWN1IgogIH0sCiAgInNlbnNvcnMiOiB7CiAgICJycG0iOiB7CiAgICAicGFyYW0iOiAicnBtIgogICB9LAogICAiY29vbGFudF90ZW1wX2MiOiB7CiAgICAicGFyYW0iOiAiY29vbGFudCIKICAgfSwKICAgImZ1ZWxfbGV2ZWxfcGN0IjogewogICAgInBhcmFtIjogImZ1ZWxfcGN0IgogICB9LAogICAiZnVlbF9yYXRlX2xwaCI6IHsKICAgICJwYXJhbSI6ICJmdWVsX3JhdGUiCiAgIH0sCiAgICJvaWxfcHJlc3N1cmVfa3BhIjogewogICAgInBhcmFtIjogIm9pbF9wIgogICB9LAogICAiZW5naW5lX2xvYWRfcGN0IjogewogICAgInBhcmFtIjogImxvYWQiCiAgIH0sCiAgICJiYXR0ZXJ5X3YiOiB7CiAgICAicGFyYW0iOiAicHdyIgogICB9LAogICAiaW1wbGVtZW50X29uIjogewogICAgInBhcmFtIjogImltcGxlbWVudCIKICAgfQogIH0KIH0sCiAiODY4MTgzMDMzNDAxOTU2IjogewogICJlZ3RzX2hvdXJzX2NvdW50ZXIiOiAxLAogICJlZ3RzX2hvdXJzX3NjYWxlIjogMC4xLAogICJzZW5zb3JzIjogewogICAiZnVlbF9sZXZlbF9sIjogewogICAgImVndHNfbGxzIjogMQogICB9LAogICAicnBtIjogewogICAgImVndHNfYW4iOiAyCiAgIH0sCiAgICJjb29sYW50X3RlbXBfYyI6IHsKICAgICJlZ3RzX2FuIjogMywKICAgICJvZmZzZXQiOiAtNDAKICAgfQogIH0KIH0sCiAiODYwMjUxMDU4OTc3NzY4Ijoge30sCiAiNzAxMTA0MyI6IHsKICAiZWd0c19ob3Vyc19jb3VudGVyIjogMSwKICAiZWd0c19ob3Vyc19zY2FsZSI6IDAuMSwKICAic2Vuc29ycyI6IHsKICAgImZ1ZWxfbGV2ZWxfbCI6IHsKICAgICJlZ3RzX2xscyI6IDEKICAgfSwKICAgInJwbSI6IHsKICAgICJlZ3RzX2FuIjogMgogICB9LAogICAiY29vbGFudF90ZW1wX2MiOiB7CiAgICAiZWd0c19hbiI6IDMsCiAgICAib2Zmc2V0IjogLTQwCiAgIH0KICB9CiB9LAogIjg2ODE4MzAzNjk2MTg0MCI6IHsKICAic2Vuc29ycyI6IHsKICAgInJwbSI6IHsKICAgICJ0YWciOiAxOTMsCiAgICAiYnl0ZV9vZmZzZXQiOiAyLAogICAgImJ5dGVzIjogMiwKICAgICJzY2FsZSI6IDAuMTI1CiAgIH0sCiAgICJjb29sYW50X3RlbXBfYyI6IHsKICAgICJ0YWciOiAxOTMsCiAgICAiYnl0ZV9vZmZzZXQiOiAxLAogICAgImJ5dGVzIjogMSwKICAgICJvZmZzZXQiOiAtNDAKICAgfSwKICAgImZ1ZWxfdXNlZF9sIjogewogICAgInRhZyI6IDE5MiwKICAgICJzY2FsZSI6IDAuNQogICB9LAogICAiZW5naW5lX2xvYWRfcGN0IjogewogICAgInRhZyI6IDE2MAogICB9LAogICAib2lsX3ByZXNzdXJlX2twYSI6IHsKICAgICJ0YWciOiAxNzYKICAgfSwKICAgImJhdHRlcnlfdiI6IHsKICAgICJ0YWciOiA2NSwKICAgICJzY2FsZSI6IDAuMDAxCiAgIH0sCiAgICJpbXBsZW1lbnRfb24iOiB7CiAgICAidGFnIjogNzAsCiAgICAiYml0IjogMQogICB9LAogICAiZnVlbF9sZXZlbF9sIjogewogICAgInRhZyI6IDk2LAogICAgInRhYmxlIjogWwogICAgIFsKICAgICAgMCwKICAgICAgMAogICAgIF0sCiAgICAgWwogICAgICA0MDk1LAogICAgICA4MDAKICAgICBdCiAgICBdCiAgIH0KICB9CiB9LAogIjg2MDI1MTA1MzEwNzM5NSI6IHt9LAogIjg2ODE4MzAzMjc4OTY4MiI6IHsKICAicGFyYW1faG91cnMiOiB7CiAgICJlbmdfaG91cnMiOiAiZWN1IgogIH0sCiAgInBhcmFtX21pbGVhZ2UiOiB7CiAgICJjYW5fZGlzdF9rbSI6ICJlY3UiCiAgfSwKICAic2Vuc29ycyI6IHsKICAgInJwbSI6IHsKICAgICJwYXJhbSI6ICJycG0iCiAgIH0sCiAgICJjb29sYW50X3RlbXBfYyI6IHsKICAgICJwYXJhbSI6ICJjb29sYW50IgogICB9LAogICAiZnVlbF9sZXZlbF9wY3QiOiB7CiAgICAicGFyYW0iOiAiZnVlbF9wY3QiCiAgIH0sCiAgICJmdWVsX3JhdGVfbHBoIjogewogICAgInBhcmFtIjogImZ1ZWxfcmF0ZSIKICAgfSwKICAgIm9pbF9wcmVzc3VyZV9rcGEiOiB7CiAgICAicGFyYW0iOiAib2lsX3AiCiAgIH0sCiAgICJlbmdpbmVfbG9hZF9wY3QiOiB7CiAgICAicGFyYW0iOiAibG9hZCIKICAgfSwKICAgImJhdHRlcnlfdiI6IHsKICAgICJwYXJhbSI6ICJwd3IiCiAgIH0sCiAgICJpbXBsZW1lbnRfb24iOiB7CiAgICAicGFyYW0iOiAiaW1wbGVtZW50IgogICB9CiAgfQogfSwKICI4NjgxODMwMzQ1MTI4OTYiOiB7CiAgInNlbnNvcnMiOiB7CiAgICJycG0iOiB7CiAgICAidGFnIjogMTkzLAogICAgImJ5dGVfb2Zmc2V0IjogMiwKICAgICJieXRlcyI6IDIsCiAgICAic2NhbGUiOiAwLjEyNQogICB9LAogICAiY29vbGFudF90ZW1wX2MiOiB7CiAgICAidGFnIjogMTkzLAogICAgImJ5dGVfb2Zmc2V0IjogMSwKICAgICJieXRlcyI6IDEsCiAgICAib2Zmc2V0IjogLTQwCiAgIH0sCiAgICJmdWVsX3VzZWRfbCI6IHsKICAgICJ0YWciOiAxOTIsCiAgICAic2NhbGUiOiAwLjUKICAgfSwKICAgImVuZ2luZV9sb2FkX3BjdCI6IHsKICAgICJ0YWciOiAxNjAKICAgfSwKICAgIm9pbF9wcmVzc3VyZV9rcGEiOiB7CiAgICAidGFnIjogMTc2CiAgIH0sCiAgICJiYXR0ZXJ5X3YiOiB7CiAgICAidGFnIjogNjUsCiAgICAic2NhbGUiOiAwLjAwMQogICB9LAogICAiaW1wbGVtZW50X29uIjogewogICAgInRhZyI6IDcwLAogICAgImJpdCI6IDEKICAgfSwKICAgImZ1ZWxfbGV2ZWxfbCI6IHsKICAgICJ0YWciOiA5NiwKICAgICJ0YWJsZSI6IFsKICAgICBbCiAgICAgIDAsCiAgICAgIDAKICAgICBdLAogICAgIFsKICAgICAgNDA5NSwKICAgICAgNDAwCiAgICAgXQogICAgXQogICB9CiAgfQogfSwKICI4NjAyNTEwNTIyODg2MTQiOiB7fSwKICI3MDExMTAyIjogewogICJlZ3RzX2hvdXJzX2NvdW50ZXIiOiAxLAogICJlZ3RzX2hvdXJzX3NjYWxlIjogMC4xLAogICJzZW5zb3JzIjogewogICAiZnVlbF9sZXZlbF9sIjogewogICAgImVndHNfbGxzIjogMQogICB9LAogICAicnBtIjogewogICAgImVndHNfYW4iOiAyCiAgIH0sCiAgICJjb29sYW50X3RlbXBfYyI6IHsKICAgICJlZ3RzX2FuIjogMywKICAgICJvZmZzZXQiOiAtNDAKICAgfQogIH0KIH0KfQ==' | base64 -d > "$DATA/mappings.json"
python3 -c "import json;a=json.load(open('$DATA/stand-state.json'));print('state:',len(a['units']),'юнитов, saved_at',a['saved_at'])"
python3 -c "import json;m=json.load(open('$DATA/mappings.json'));print('mappings:',len(m),'IMEI')"

say "4) остановить прежний стенд (если был) и запустить"
pkill -f "$APP_DIR/stand/run.sh" 2>/dev/null || true
sleep 1
nohup "$APP_DIR/stand/run.sh" > "$APP_DIR/stand/nohup.log" 2>&1 &
sleep 4

say "5) @reboot в cron (переживает перезагрузку VPS)"
if command -v crontab >/dev/null; then
  (crontab -l 2>/dev/null | grep -v "stand/run.sh"; echo "@reboot $APP_DIR/stand/run.sh > $APP_DIR/stand/nohup.log 2>&1") | crontab -
  echo "cron ok"
else
  echo "!! crontab нет — добавьте @reboot вручную: $APP_DIR/stand/run.sh"
fi

say "6) проверки"
for p in 5034 5037 5039 5041 5090; do
  python3 -c "import socket,sys;s=socket.socket();s.settimeout(2);sys.exit(0 if s.connect_ex(('127.0.0.1',$p))==0 else 1)" \
    && echo "порт $p: слушается" || echo "!! порт $p: НЕ слушается"
done
sleep 8
if [ -f "$DATA/gateway-status.json" ]; then
  python3 -c "import json;s=json.load(open('$DATA/gateway-status.json'));print('шлюз: connections',s['connections'],'queue',s['queue'],'errors',s['errors'],'last_error',s['last_error'])"
fi
tail -n 5 "$DATA/stand.log" 2>/dev/null || true
echo
echo "Готово. Логи: $DATA/{stand,gateway}.log. Остановить: pkill -f '$APP_DIR/stand/run.sh'"
echo "Карточка стенда в кабинете: id=$STAND_ID (та же, что была с песочницы)."
