#!/usr/bin/env bash
# Единый перенос живого стенда ITles (шлюз + симулятор парка) с песочницы Zo на VPS.
# Запускать НА VPS от обычного пользователя (agentuser):
#
#   STAND_KEY='itg_...' bash stand-migrate-vps.sh
#
# STAND_KEY — ключ шлюза вида itg_… (Настройки → Ключи шлюзов; хэш уже зарегистрирован в БД).
# Скрипт идемпотентен: повторный запуск обновляет код/данные и перезапускает процессы.
#
# Что делает:
#   1) клон/обновление репо raulwulff6769/framework-lab @otschet-current (тот же клон, где сайт);
#   2) stand/stand.env: API = локальный сервер сайта (http://127.0.0.1:3000), STAND_ID прежний
#      (stand-vps) — карточка стенда в кабинете не задваивается;
#   3) данные стенда (.stand/stand-state.json — счётчики моточасов/пробега, mappings.json —
#      конфиг датчиков Galileosky) восстанавливаются из вшитых ниже base64 — телеметрия в БД
#      (Neon) уже общая, поэтому история 30 дней переносится автоматически;
#   4) запуск stand/run.sh (супервизор шлюза и стенда) + @reboot в cron;
#   5) проверки: порты шлюза слушаются, стенд отчитался в API (HTTP 200).
#
# Очередь неотправленных пакетов (gateway-queue.sqlite3) НЕ переносится: пока песочница Zo ещё
# работает, её шлюз дольёт очередь в API сам (ключ валиден). После запуска на VPS стенд
# продолжает с текущего момента — разрыва в истории не будет, если сначала дать Zo-стенду
# выкачать очередь до нуля (status .stand/gateway-status.json → queue: 0).
set -euo pipefail

APP_DIR="${APP_DIR:-$HOME/itles}"
BRANCH="${BRANCH:-otschet-current}"
REPO="${REPO:-https://github.com/raulwulff6769/framework-lab.git}"
API_URL="${API_URL:-http://127.0.0.1:3000}"
STAND_ID="${STAND_ID:-stand-vps}"
HOST_LABEL="${HOST_LABEL:-VPS Singapore (Tencent)}"

say(){ printf '\n\033[1;36m== %s ==\033[0m\n' "$1"; }
[ -n "${STAND_KEY:-}" ] || { echo "!! задайте STAND_KEY (ключ шлюза itg_...) перед запуском"; exit 1; }
command -v python3 >/dev/null || { echo "!! нужен python3 (apt-get install -y python3)"; exit 1; }
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' || { echo "!! нужен Python 3.10+"; exit 1; }

say "1) код стенда: $APP_DIR @ $BRANCH"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" fetch --depth 1 origin "$BRANCH"
  git -C "$APP_DIR" checkout -q -B "$BRANCH" "origin/$BRANCH"
else
  git clone --depth 1 -b "$BRANCH" "$REPO" "$APP_DIR"
fi
git -C "$APP_DIR" log --oneline -1

say "2) конфиг stand.env (API=$API_URL)"
ENV="$APP_DIR/stand/stand.env"
cat > "$ENV" <<EOF
ITLES_API_URL=$API_URL
STAND_KEY=$STAND_KEY
STAND_ID=$STAND_ID
STAND_HOST_LABEL="$HOST_LABEL"
STAND_HISTORY_DAYS=30
TRACCAR_HOST=demo.traccar.org
TRACCAR_PORT_TELTONIKA=5027
TRACCAR_WEB=https://demo.traccar.org
EOF
chmod 600 "$ENV"

say "3) состояние парка и конфиг датчиков (из песочницы Zo)"
DATA="$APP_DIR/.stand"
mkdir -p "$DATA" && chmod 700 "$DATA"
printf '%s' 'eyJ2ZXJzaW9uIjogMSwgInNhdmVkX2F0IjogMTc5MDY1Mjk2OC44MjI4NzY3LCAidW5pdHMiOiB7Ijg2ODE4MzAzMDgyODkwNCI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDQ0NTUuNTQ5MjE2ODgwNzc3LCAib2RvX20iOiAzMDM2Njk3MS4wODUxMTE2MzMsICJnbnNzX29kb19tIjogMzk1MDk3MS4wODUxMTIyNzEsICJmdWVsX3VzZWRfbCI6IDEzMjExMS4yNDMyMjg0MDE1MiwgImZ1ZWxfbCI6IDkwOC40ODE3NTk1OTkzMzA0LCAiaW5kZXgiOiA3NTA5fSwgIjg2MDI1MTA1NTc4MzA0NSI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDUxMzMuMjU2ODc4ODUzNjMxLCAib2RvX20iOiAzNDg3OTI5MS45NjI3NDg0MTYsICJnbnNzX29kb19tIjogNDA3NzA5MS45NjI3NDYyOTQsICJmdWVsX3VzZWRfbCI6IDE1MDk1My4yNzc0OTk0MTA0NCwgImZ1ZWxfbCI6IDc2Ni40NDE4OTg2NTU5NDEzLCAiaW5kZXgiOiA2NzAxfSwgIjg2ODE4MzAzNjQ1Nzg1NiI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDE3MzYuNDEyODY3NzE5NTk3MiwgIm9kb19tIjogMTE1OTQyMDguNTgwMzAwMTY1LCAiZ25zc19vZG9fbSI6IDI2NDUwMDguNTgwMjk5Mzg1NCwgImZ1ZWxfdXNlZF9sIjogNDgyODAuOTAxODYxNzA0NzgsICJmdWVsX2wiOiA4MDMuMzI2NDIxNDcyNTgxMywgImluZGV4IjogNTg5Mn0sICI4NjgxODMwMzM0MDE5NTYiOiB7InQiOiAxNzkwNjUyOTY4LCAiaG91cnMiOiAyNjc4Ny41NzgzNzAxOTk3NDYsICJvZG9fbSI6IDE3MjE2MDI1Mi44ODk4NzY2LCAiZ25zc19vZG9fbSI6IDE2Mjc1NTIuODg5ODgxMTg3NCwgImZ1ZWxfdXNlZF9sIjogMjY3NDEwLjk1NjAyNzE2NDM2LCAiZnVlbF9sIjogMjQ2LjQxMTAwNjczNDI4NzQ0LCAiaW5kZXgiOiAzNjk3fSwgIjg2MDI1MTA1ODk3Nzc2OCI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDE1NzQzLjk5NTAzNjUzNTA5LCAib2RvX20iOiAxMDExOTU3MTUuMjM0MzIzMTYsICJnbnNzX29kb19tIjogMjI0ODE2NS4yMzQzMjMxNjMsICJmdWVsX3VzZWRfbCI6IDEyOTAxNi40NjA1NDAwMzcxLCAiZnVlbF9sIjogODIuNjA5MTQ0OTk4NjY1NSwgImluZGV4IjogNTYyM30sICI3MDExMDQzIjogeyJ0IjogMTc5MDY1Mjk2OCwgImhvdXJzIjogMjM2NjMuMzk3NjYxMTE2MjIsICJvZG9fbSI6IDE2NDMwMjY0OS45OTI2MDc3NywgImduc3Nfb2RvX20iOiAxMzQ0OTk5OS45OTI2MDYzMSwgImZ1ZWxfdXNlZF9sIjogNDc3MzQ2LjAxMDQ5NzQ5NTUzLCAiZnVlbF9sIjogMzAyLjMzOTY2OTI1NTEwNjUsICJpbmRleCI6IDkzNzh9LCAiODY4MTgzMDM2OTYxODQwIjogeyJ0IjogMTc5MDY1Mjk2OCwgImhvdXJzIjogMzQ1MjAuNzQyNTE3MTIzOTgsICJvZG9fbSI6IDIyNzMyMzgzOS42OTU0OTE5LCAiZ25zc19vZG9fbSI6IDY3NDk1ODkuNjk1NDk5Nzg1LCAiZnVlbF91c2VkX2wiOiAxNDkxMDMzLjQ5MDMwMjM1MjIsICJmdWVsX2wiOiA2MjAuNDA2MTczMDI0ODM2OCwgImluZGV4IjogODUzNH0sICI4NjAyNTEwNTMxMDczOTUiOiB7InQiOiAxNzkwNjUyOTY4LCAiaG91cnMiOiAxMjcwOC4xOTMyMDcyOTkxNSwgIm9kb19tIjogODE1ODgyODIuNTkxMDA0NTcsICJnbnNzX29kb19tIjogMjU3NzUzMi41OTEwMDA5MjksICJmdWVsX3VzZWRfbCI6IDE2MzMxNi4xODg3MjE2NTg5MiwgImZ1ZWxfbCI6IDE4NC4zMjIwMTQyMzI2MDU3LCAiaW5kZXgiOiAxMDYyNH0sICI4NjgxODMwMzI3ODk2ODIiOiB7InQiOiAxNzkwNjUyOTY4LCAiaG91cnMiOiAxMzk1MS40MjUzMzQ0MTU4NSwgIm9kb19tIjogMC4wLCAiZ25zc19vZG9fbSI6IDEzNDQ3MTYuMTEzNDcxNTk1LCAiZnVlbF91c2VkX2wiOiAyNzA2NDguNjIzMjgzMjE4MjQsICJmdWVsX2wiOiAzNTMuMTA3NTg0MjUzMTYyNiwgImluZGV4IjogOTgwNn0sICIzNTIxMDIxMjc0MDgyODIiOiB7InQiOiAxNzkwNjUyOTY4LCAiaG91cnMiOiAyMDUxLjk1MTQ5Nzk4OTIzMDYsICJvZG9fbSI6IDEzNzY4NTExLjA5NzI5MTQ4NCwgImduc3Nfb2RvX20iOiAxMjU1MzYxLjA5NzI5MTM5MjcsICJmdWVsX3VzZWRfbCI6IDU5ODU5Ljk0MzIyMjc0ODA2NSwgImZ1ZWxfbCI6IDU3Mi44NzgyMzgxNTM2NzE2LCAiaW5kZXgiOiAyMjI2fSwgIjM1MjEwMjEyNDYxMjcyMCI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDQ4NTcuMjIyMzIwMDI1NjU4NSwgIm9kb19tIjogMC4wLCAiZ25zc19vZG9fbSI6IDY0MzAxLjg5Nzc4OTIwMjE3LCAiZnVlbF91c2VkX2wiOiAxMDkxODMuODYzNzcxNzMxNjUsICJmdWVsX2wiOiA0MTEuODUyNDEyNjIxMjM1NiwgImluZGV4IjogNTU0fSwgIjM1MjEwMjEyMDA0NjM2MCI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDQ2MjkuODIyMDIwMDc1NzEzLCAib2RvX20iOiAyOTk3Mzk5OC42NzI2OTA3MDQsICJnbnNzX29kb19tIjogODU5ODQ4LjY3MjY5MDE3OTEsICJmdWVsX3VzZWRfbCI6IDU5MTU2LjMxOTk5OTg1OTc5LCAiZnVlbF9sIjogNzQuMTEyODM1NjM4Njg4MTcsICJpbmRleCI6IDI5NDF9LCAiODY4MTgzMDMxMjQ1NjcwIjogeyJ0IjogMTc5MDY1Mjk2OCwgImhvdXJzIjogODEwMi40NzI5OTk1NTExOTMsICJvZG9fbSI6IDUyMTczNzIzLjMzNDU5ODUyLCAiZ25zc19vZG9fbSI6IDYwNjYyMy4zMzQ1OTc5MzI5LCAiZnVlbF91c2VkX2wiOiA4MDgxOC44MDgxMjMxMTcxOCwgImZ1ZWxfbCI6IDI2NC4xNzE2OTYzNjI5MDI4LCAiaW5kZXgiOiAxNDg4fSwgIjg2ODE4MzAzMTI0NTY4OCI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDcyOTkuODM0MTEwNjYyMzk3NSwgIm9kb19tIjogNDcyMTk3OTQuNTU3ODg4MzIsICJnbnNzX29kb19tIjogODI4NjQ0LjU1Nzg4ODY0NDMsICJmdWVsX3VzZWRfbCI6IDU5NTYzLjIzNjE2NjgyNjEzLCAiZnVlbF9sIjogNTMuNTQxNTQ5MjI2NTYwODA0LCAiaW5kZXgiOiAxOTkwfSwgIjg2ODE4MzAzMTI0NTY5NiI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDYwNzMuMTE0NTEyNzUwNzksICJvZG9fbSI6IDQxODE3NjQ1LjgxMjA2NzYxLCAiZ25zc19vZG9fbSI6IDMyMTczOTUuODEyMDY3NTE5LCAiZnVlbF91c2VkX2wiOiAxMjIzNTAuMzExMzEyODMxOTIsICJmdWVsX2wiOiA0NDAuMjk0NTk0ODQxMzczOCwgImluZGV4IjogMjM5NH0sICJLTVRQQzIyOUwwMTA0NTEyMyI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDUxNDAuMjY5ODI5MzU5MTg5LCAib2RvX20iOiAwLjAsICJnbnNzX29kb19tIjogNzQzNjcuMjg3MjQ1MDY2MDIsICJmdWVsX3VzZWRfbCI6IDExNTI5Ni4zNTUzNzYyMDcxLCAiZnVlbF9sIjogNTU0LjMzOTQyMTg3MTI1OTEsICJpbmRleCI6IDU3OX0sICJLTVRIRDQ2NUswNzAzMjk4MSI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDY5NjUuNTI0MTE1NTUwMzM5LCAib2RvX20iOiA0NjQ5ODQwNi4wNzYyMzY0MywgImduc3Nfb2RvX20iOiAyNjM3NzA2LjA3NjIzNjEyOSwgImZ1ZWxfdXNlZF9sIjogMzAzNDQwLjIzOTEzOTk4OTI1LCAiZnVlbF9sIjogNTUyLjEyMjIwNTgyMjYxNjYsICJpbmRleCI6IDMxMjZ9LCAiS01UV0E0NzBWNjUwMjE0NTUiOiB7InQiOiAxNzkwNjUyOTY4LCAiaG91cnMiOiA0MTAzLjQxOTc2NTM3MjAxOCwgIm9kb19tIjogMjY0MjA4MTAuODEyMjIxOTE1LCAiZ25zc19vZG9fbSI6IDcwNzQ2MC44MTIyMjEzNjI0LCAiZnVlbF91c2VkX2wiOiA1MjU1NC4xNzQ0MTEzMDYyNywgImZ1ZWxfbCI6IDE5My4yOTUxMzcyMjEzNTc3NSwgImluZGV4IjogMjk4Nn0sICI4NjgxODMwMzQ1MTI4OTYiOiB7InQiOiAxNzkwNjUyOTY4LCAiaG91cnMiOiA1NzEzLjA5MDMxNzY3NTkwMSwgIm9kb19tIjogMC4wLCAiZ25zc19vZG9fbSI6IDQ0MTQ1LjQ2NzQwNDc4NzAxLCAiZnVlbF91c2VkX2wiOiAxMjc3NTQuNjk5NTU0NzE2NywgImZ1ZWxfbCI6IDE3My43NjAxMjI1OTQ1NjczNSwgImluZGV4IjogNDA1fSwgIjg2MDI1MTA1MjI4ODYxNCI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDY4OTguMzM0MTA0OTc3NDMzLCAib2RvX20iOiA0NTY5NjkzOC43NzcyMDU4NTUsICJnbnNzX29kb19tIjogMjIyNDkzOC43NzcyMDQ4LCAiZnVlbF91c2VkX2wiOiAzMDAzODUuOTA1OTA3NTQzOTYsICJmdWVsX2wiOiAxNDEuMzkzNDQyNjI0NjU5NzQsICJpbmRleCI6IDM0MDF9LCAiNzAxMTEwMiI6IHsidCI6IDE3OTA2NTI5NjgsICJob3VycyI6IDQ0NzcuNjQ3MTc3ODgxNjQ4LCAib2RvX20iOiAwLjAsICJnbnNzX29kb19tIjogMzczNjU5LjYyNTg1NzQyNjIsICJmdWVsX3VzZWRfbCI6IDg2NTM3Ljk0MjI3NzAxNzEyLCAiZnVlbF9sIjogMjA3LjcwOTUxMjk5MjIwODk0LCAiaW5kZXgiOiAyODE0fX19' | base64 -d > "$DATA/stand-state.json"
printf '%s' 'ewogIjg2ODE4MzAzMDgyODkwNCI6IHsKICAic2Vuc29ycyI6IHsKICAgInJwbSI6IHsKICAgICJ0YWciOiAxOTMsCiAgICAiYnl0ZV9vZmZzZXQiOiAyLAogICAgImJ5dGVzIjogMiwKICAgICJzY2FsZSI6IDAuMTI1CiAgIH0sCiAgICJjb29sYW50X3RlbXBfYyI6IHsKICAgICJ0YWciOiAxOTMsCiAgICAiYnl0ZV9vZmZzZXQiOiAxLAogICAgImJ5dGVzIjogMSwKICAgICJvZmZzZXQiOiAtNDAKICAgfSwKICAgImZ1ZWxfdXNlZF9sIjogewogICAgInRhZyI6IDE5MiwKICAgICJzY2FsZSI6IDAuNQogICB9LAogICAiZW5naW5lX2xvYWRfcGN0IjogewogICAgInRhZyI6IDE2MAogICB9LAogICAib2lsX3ByZXNzdXJlX2twYSI6IHsKICAgICJ0YWciOiAxNzYKICAgfSwKICAgImJhdHRlcnlfdiI6IHsKICAgICJ0YWciOiA2NSwKICAgICJzY2FsZSI6IDAuMDAxCiAgIH0sCiAgICJpbXBsZW1lbnRfb24iOiB7CiAgICAidGFnIjogNzAsCiAgICAiYml0IjogMQogICB9LAogICAiZnVlbF9sZXZlbF9sIjogewogICAgInRhZyI6IDk2LAogICAgInRhYmxlIjogWwogICAgIFsKICAgICAgMCwKICAgICAgMAogICAgIF0sCiAgICAgWwogICAgICA0MDk1LAogICAgICAxMDAwCiAgICAgXQogICAgXQogICB9CiAgfQogfSwKICI4NjAyNTEwNTU3ODMwNDUiOiB7fSwKICI4NjgxODMwMzY0NTc4NTYiOiB7CiAgInBhcmFtX2hvdXJzIjogewogICAiZW5nX2hvdXJzIjogImVjdSIKICB9LAogICJwYXJhbV9taWxlYWdlIjogewogICAiY2FuX2Rpc3Rfa20iOiAiZWN1IgogIH0sCiAgInNlbnNvcnMiOiB7CiAgICJycG0iOiB7CiAgICAicGFyYW0iOiAicnBtIgogICB9LAogICAiY29vbGFudF90ZW1wX2MiOiB7CiAgICAicGFyYW0iOiAiY29vbGFudCIKICAgfSwKICAgImZ1ZWxfbGV2ZWxfcGN0IjogewogICAgInBhcmFtIjogImZ1ZWxfcGN0IgogICB9LAogICAiZnVlbF9yYXRlX2xwaCI6IHsKICAgICJwYXJhbSI6ICJmdWVsX3JhdGUiCiAgIH0sCiAgICJvaWxfcHJlc3N1cmVfa3BhIjogewogICAgInBhcmFtIjogIm9pbF9wIgogICB9LAogICAiZW5naW5lX2xvYWRfcGN0IjogewogICAgInBhcmFtIjogImxvYWQiCiAgIH0sCiAgICJiYXR0ZXJ5X3YiOiB7CiAgICAicGFyYW0iOiAicHdyIgogICB9LAogICAiaW1wbGVtZW50X29uIjogewogICAgInBhcmFtIjogImltcGxlbWVudCIKICAgfQogIH0KIH0sCiAiODY4MTgzMDMzNDAxOTU2IjogewogICJlZ3RzX2hvdXJzX2NvdW50ZXIiOiAxLAogICJlZ3RzX2hvdXJzX3NjYWxlIjogMC4xLAogICJzZW5zb3JzIjogewogICAiZnVlbF9sZXZlbF9sIjogewogICAgImVndHNfbGxzIjogMQogICB9LAogICAicnBtIjogewogICAgImVndHNfYW4iOiAyCiAgIH0sCiAgICJjb29sYW50X3RlbXBfYyI6IHsKICAgICJlZ3RzX2FuIjogMywKICAgICJvZmZzZXQiOiAtNDAKICAgfQogIH0KIH0sCiAiODYwMjUxMDU4OTc3NzY4Ijoge30sCiAiNzAxMTA0MyI6IHsKICAiZWd0c19ob3Vyc19jb3VudGVyIjogMSwKICAiZWd0c19ob3Vyc19zY2FsZSI6IDAuMSwKICAic2Vuc29ycyI6IHsKICAgImZ1ZWxfbGV2ZWxfbCI6IHsKICAgICJlZ3RzX2xscyI6IDEKICAgfSwKICAgInJwbSI6IHsKICAgICJlZ3RzX2FuIjogMgogICB9LAogICAiY29vbGFudF90ZW1wX2MiOiB7CiAgICAiZWd0c19hbiI6IDMsCiAgICAib2Zmc2V0IjogLTQwCiAgIH0KICB9CiB9LAogIjg2ODE4MzAzNjk2MTg0MCI6IHsKICAic2Vuc29ycyI6IHsKICAgInJwbSI6IHsKICAgICJ0YWciOiAxOTMsCiAgICAiYnl0ZV9vZmZzZXQiOiAyLAogICAgImJ5dGVzIjogMiwKICAgICJzY2FsZSI6IDAuMTI1CiAgIH0sCiAgICJjb29sYW50X3RlbXBfYyI6IHsKICAgICJ0YWciOiAxOTMsCiAgICAiYnl0ZV9vZmZzZXQiOiAxLAogICAgImJ5dGVzIjogMSwKICAgICJvZmZzZXQiOiAtNDAKICAgfSwKICAgImZ1ZWxfdXNlZF9sIjogewogICAgInRhZyI6IDE5MiwKICAgICJzY2FsZSI6IDAuNQogICB9LAogICAiZW5naW5lX2xvYWRfcGN0IjogewogICAgInRhZyI6IDE2MAogICB9LAogICAib2lsX3ByZXNzdXJlX2twYSI6IHsKICAgICJ0YWciOiAxNzYKICAgfSwKICAgImJhdHRlcnlfdiI6IHsKICAgICJ0YWciOiA2NSwKICAgICJzY2FsZSI6IDAuMDAxCiAgIH0sCiAgICJpbXBsZW1lbnRfb24iOiB7CiAgICAidGFnIjogNzAsCiAgICAiYml0IjogMQogICB9LAogICAiZnVlbF9sZXZlbF9sIjogewogICAgInRhZyI6IDk2LAogICAgInRhYmxlIjogWwogICAgIFsKICAgICAgMCwKICAgICAgMAogICAgIF0sCiAgICAgWwogICAgICA0MDk1LAogICAgICA4MDAKICAgICBdCiAgICBdCiAgIH0KICB9CiB9LAogIjg2MDI1MTA1MzEwNzM5NSI6IHt9LAogIjg2ODE4MzAzMjc4OTY4MiI6IHsKICAicGFyYW1faG91cnMiOiB7CiAgICJlbmdfaG91cnMiOiAiZWN1IgogIH0sCiAgInBhcmFtX21pbGVhZ2UiOiB7CiAgICJjYW5fZGlzdF9rbSI6ICJlY3UiCiAgfSwKICAic2Vuc29ycyI6IHsKICAgInJwbSI6IHsKICAgICJwYXJhbSI6ICJycG0iCiAgIH0sCiAgICJjb29sYW50X3RlbXBfYyI6IHsKICAgICJwYXJhbSI6ICJjb29sYW50IgogICB9LAogICAiZnVlbF9sZXZlbF9wY3QiOiB7CiAgICAicGFyYW0iOiAiZnVlbF9wY3QiCiAgIH0sCiAgICJmdWVsX3JhdGVfbHBoIjogewogICAgInBhcmFtIjogImZ1ZWxfcmF0ZSIKICAgfSwKICAgIm9pbF9wcmVzc3VyZV9rcGEiOiB7CiAgICAicGFyYW0iOiAib2lsX3AiCiAgIH0sCiAgICJlbmdpbmVfbG9hZF9wY3QiOiB7CiAgICAicGFyYW0iOiAibG9hZCIKICAgfSwKICAgImJhdHRlcnlfdiI6IHsKICAgICJwYXJhbSI6ICJwd3IiCiAgIH0sCiAgICJpbXBsZW1lbnRfb24iOiB7CiAgICAicGFyYW0iOiAiaW1wbGVtZW50IgogICB9CiAgfQogfSwKICI4NjgxODMwMzQ1MTI4OTYiOiB7CiAgInNlbnNvcnMiOiB7CiAgICJycG0iOiB7CiAgICAidGFnIjogMTkzLAogICAgImJ5dGVfb2Zmc2V0IjogMiwKICAgICJieXRlcyI6IDIsCiAgICAic2NhbGUiOiAwLjEyNQogICB9LAogICAiY29vbGFudF90ZW1wX2MiOiB7CiAgICAidGFnIjogMTkzLAogICAgImJ5dGVfb2Zmc2V0IjogMSwKICAgICJieXRlcyI6IDEsCiAgICAib2Zmc2V0IjogLTQwCiAgIH0sCiAgICJmdWVsX3VzZWRfbCI6IHsKICAgICJ0YWciOiAxOTIsCiAgICAic2NhbGUiOiAwLjUKICAgfSwKICAgImVuZ2luZV9sb2FkX3BjdCI6IHsKICAgICJ0YWciOiAxNjAKICAgfSwKICAgIm9pbF9wcmVzc3VyZV9rcGEiOiB7CiAgICAidGFnIjogMTc2CiAgIH0sCiAgICJiYXR0ZXJ5X3YiOiB7CiAgICAidGFnIjogNjUsCiAgICAic2NhbGUiOiAwLjAwMQogICB9LAogICAiaW1wbGVtZW50X29uIjogewogICAgInRhZyI6IDcwLAogICAgImJpdCI6IDEKICAgfSwKICAgImZ1ZWxfbGV2ZWxfbCI6IHsKICAgICJ0YWciOiA5NiwKICAgICJ0YWJsZSI6IFsKICAgICBbCiAgICAgIDAsCiAgICAgIDAKICAgICBdLAogICAgIFsKICAgICAgNDA5NSwKICAgICAgNDAwCiAgICAgXQogICAgXQogICB9CiAgfQogfSwKICI4NjAyNTEwNTIyODg2MTQiOiB7fSwKICI3MDExMTAyIjogewogICJlZ3RzX2hvdXJzX2NvdW50ZXIiOiAxLAogICJlZ3RzX2hvdXJzX3NjYWxlIjogMC4xLAogICJzZW5zb3JzIjogewogICAiZnVlbF9sZXZlbF9sIjogewogICAgImVndHNfbGxzIjogMQogICB9LAogICAicnBtIjogewogICAgImVndHNfYW4iOiAyCiAgIH0sCiAgICJjb29sYW50X3RlbXBfYyI6IHsKICAgICJlZ3RzX2FuIjogMywKICAgICJvZmZzZXQiOiAtNDAKICAgfQogIH0KIH0KfQ==' | base64 -d > "$DATA/mappings.json"
python3 -c "import json;a=json.load(open('$DATA/stand-state.json'));print('state:',len(a['units']),'юнитов, saved_at',a['saved_at'])"
python3 -c "import json;m=json.load(open('$DATA/mappings.json'));print('mappings:',len(m),'IMEI')"

say "4) остановить прежний стенд (если был) и запустить"
pkill -f "$APP_DIR/stand/run.sh" 2>/dev/null || true
sleep 1
nohup "$APP_DIR/stand/run.sh" > "$APP_DIR/stand/nohup.log" 2>&1 &
sleep 4

say "5) @reboot в cron (переживает перезагрузку VPS)"
if command -v crontab >/dev/null; then
  (crontab -l 2>/dev/null | grep -v "stand/run.sh"; echo "@reboot $APP_DIR/stand/run.sh > $APP_DIR/stand/nohup.log 2>&1") | crontab -
  echo "cron ok"
else
  echo "!! crontab нет — добавьте @reboot вручную: $APP_DIR/stand/run.sh"
fi

say "6) проверки"
for p in 5034 5037 5039 5041 5090; do
  python3 -c "import socket,sys;s=socket.socket();s.settimeout(2);sys.exit(0 if s.connect_ex(('127.0.0.1',$p))==0 else 1)" \
    && echo "порт $p: слушается" || echo "!! порт $p: НЕ слушается"
done
sleep 8
if [ -f "$DATA/gateway-status.json" ]; then
  python3 -c "import json;s=json.load(open('$DATA/gateway-status.json'));print('шлюз: connections',s['connections'],'queue',s['queue'],'errors',s['errors'],'last_error',s['last_error'])"
fi
tail -n 5 "$DATA/stand.log" 2>/dev/null || true
echo
echo "Готово. Логи: $DATA/{stand,gateway}.log. Остановить: pkill -f '$APP_DIR/stand/run.sh'"
echo "Карточка стенда в кабинете: id=$STAND_ID (та же, что была с песочницы)."
